/**********************************************************/
/* 1.- Sentencias de borrado de todas las tablas y vistas */
/**********************************************************/
DROP TABLE EMPLEADOS CASCADE CONSTRAINTS;
DROP TABLE ANALISTAS CASCADE CONSTRAINTS;
DROP TABLE TECNICOS CASCADE CONSTRAINTS;
DROP TABLE PILOTOS CASCADE CONSTRAINTS;
DROP TABLE PILOTO_COMERCIAL CASCADE CONSTRAINTS;
DROP TABLE ORG_MARKETING CASCADE CONSTRAINTS;
DROP TABLE PATROCINADORES CASCADE CONSTRAINTS;
DROP TABLE PERSONA CASCADE CONSTRAINTS;
DROP TABLE EMPRESA CASCADE CONSTRAINTS;
DROP TABLE ESCUD CASCADE CONSTRAINTS;
DROP TABLE SETUP CASCADE CONSTRAINTS;
DROP TABLE COCHE CASCADE CONSTRAINTS;
DROP TABLE GP CASCADE CONSTRAINTS;
DROP TABLE CARRERA CASCADE CONSTRAINTS;
DROP TABLE ENTREN CASCADE CONSTRAINTS;
DROP TABLE PIEZA CASCADE CONSTRAINTS;
DROP TABLE VERSION CASCADE CONSTRAINTS;
DROP TABLE COMPONENTES CASCADE CONSTRAINTS;
DROP TABLE MOTOR CASCADE CONSTRAINTS;
DROP TABLE CAJA_DE_CAMBIOS CASCADE CONSTRAINTS;
DROP TABLE SUSPENSION CASCADE CONSTRAINTS;
DROP TABLE FRENOS CASCADE CONSTRAINTS;
DROP TABLE KIT_AERO CASCADE CONSTRAINTS;
DROP TABLE COBERTURA_MOTOR CASCADE CONSTRAINTS;
DROP TABLE PONTON CASCADE CONSTRAINTS;
DROP TABLE ALERON_DEL CASCADE CONSTRAINTS;
DROP TABLE ALERON_TRAS CASCADE CONSTRAINTS;
DROP TABLE MGU_K CASCADE CONSTRAINTS;
DROP TABLE MGU_H CASCADE CONSTRAINTS;
DROP TABLE BATERIA CASCADE CONSTRAINTS;
DROP TABLE NEUMATICOS CASCADE CONSTRAINTS;
DROP TABLE SLICS CASCADE CONSTRAINTS;
DROP TABLE WET CASCADE CONSTRAINTS;

DROP VIEW V_PIEZAS;
DROP VIEW V_EMPLEADOS;
DROP VIEW V_COCHES;

DROP INDEX Estado_Neumaticos;

/**************************************************/
/* 2.- Creamos las tablas de nuestro Diagrama EER */
/**************************************************/
CREATE TABLE ESCUD
(
    ESCUDID     VARCHAR2(15),
    ESCUDNAME   VARCHAR2(12),
    ESCUDPUNT   NUMBER(4),
    ESCUDPRESU  NUMBER(7),
    PRIMARY KEY(ESCUDID)
);
CREATE TABLE GP
(
    IDGP    VARCHAR2(12),
    FECHAGP DATE,
    LOCGP   VARCHAR2(12),
    PRIMARY KEY(IDGP)
);

CREATE TABLE COCHE
(
    IDCOCHE VARCHAR2(12) NOT NULL,
    FECHAMONTAJE DATE NOT NULL,
    PESOCOCHE    NUMBER(5) NOT NULL,
    PRECIOCOCHE NUMBER(6) NOT NULL,
    ESTADOCOCHE VARCHAR2(20) NOT NULL,
    ESCUDID VARCHAR2(12) NOT NULL,
    PRIMARY KEY(IDCOCHE),
        FOREIGN KEY (ESCUDID) REFERENCES ESCUD
);
CREATE TABLE PIEZA(
    NUM_PIEZA NUMBER(4) NOT NULL PRIMARY KEY
);
CREATE TABLE VERSION(
    NUM_PIEZA NUMBER(6) NOT NULL REFERENCES PIEZA,
    NUM_VERSION NUMBER(6) NOT NULL,
    PRIMARY KEY(NUM_PIEZA,NUM_VERSION)
);

CREATE TABLE EMPLEADOS(
    DNI VARCHAR2(9) NOT NULL,
    F_INICIOCONTRATO DATE,
    DIRECCION VARCHAR2(10) NOT NULL,
    NSS VARCHAR2(12) NOT NULL,
    SUELDO NUMBER(8,2),
    NOMBRE VARCHAR2(10) NOT NULL,
    APELLIDOS VARCHAR2(10) NOT NULL,
    ESCUDID VARCHAR2(15),
    PRIMARY KEY(DNI),
    FOREIGN KEY(ESCUDID) REFERENCES ESCUD,
    CONSTRAINT SSOCIAL UNIQUE(NSS)
);
ALTER TABLE EMPLEADOS ADD ID_DIRIGENTE REFERENCES EMPLEADOS;

CREATE TABLE SETUP(
    ID_SETUP VARCHAR2(20) NOT NULL,
    CAIDA NUMBER(2) NOT NULL,
    AVANCE NUMBER(2) NOT NULL,
    ALINEACION NUMBER(2) NOT NULL,
    IDCOCHE VARCHAR2(12) NOT NULL,
    PRIMARY KEY(ID_SETUP),
    FOREIGN KEY(IDCOCHE) REFERENCES COCHE
);
CREATE TABLE ANALISTAS(
    DNI VARCHAR2(9)NOT NULL,
    ESTADISTICAS VARCHAR2(12),
    ESPECIALIZACION VARCHAR2(2),
    ID_SETUP VARCHAR2(20) NOT NULL,
    FOREIGN KEY(DNI) REFERENCES EMPLEADOS,
    FOREIGN KEY(ID_SETUP) REFERENCES SETUP,
    PRIMARY KEY(DNI),
    CHECK(ESPECIALIZACION IN ('MOJADO','SECO'))
);

CREATE TABLE TECNICOS(
    DNI VARCHAR2(9) NOT NULL,
    ESPECIALIZACION VARCHAR2(9),
    NUM_VERSION NUMBER(6) NOT NULL,
    NUM_PIEZA NUMBER(6) NOT NULL,
    FOREIGN KEY(NUM_VERSION,NUM_PIEZA) REFERENCES VERSION,
    FOREIGN KEY(DNI) REFERENCES EMPLEADOS,
    PRIMARY KEY(DNI),
    CHECK(ESPECIALIZACION IN ('NEUMATICOS','BATERIA','MGU-H','MUG-K','KIT_AERO','FRENOS','SUSPENSION','CAJA_DE_CAMBIOS','MOTOR'))
);

CREATE TABLE PILOTOS(
    DNI VARCHAR2(9)NOT NULL,
    PUNTUACIONPILOTO VARCHAR2(12),
    PUESTO VARCHAR2(12),
    IDGP VARCHAR2(12) NOT NULL,
    IDCOCHE VARCHAR2(12) NOT NULL,
    FOREIGN KEY(IDGP) REFERENCES GP,
    FOREIGN KEY(DNI) REFERENCES EMPLEADOS,
    FOREIGN KEY(IDCOCHE) REFERENCES COCHE,
    PRIMARY KEY(DNI)
);
CREATE TABLE ORG_MARKETING(
    DNI VARCHAR2(9)NOT NULL,
    PRESUPUESTO VARCHAR2(12),
    
    FOREIGN KEY(DNI) REFERENCES EMPLEADOS,
    PRIMARY KEY(DNI)
);

CREATE TABLE PILOTO_COMERCIAL(
    DNI VARCHAR2(9)NOT NULL,
    EXTRA VARCHAR2(12),
    FOREIGN KEY(DNI) REFERENCES PILOTOS,
    FOREIGN KEY(DNI) REFERENCES ORG_MARKETING
);



CREATE TABLE PATROCINADORES(
    NSS VARCHAR2(12) NOT NULL,
    FECHAINICIO VARCHAR2(12),
    FECHAFIN VARCHAR2(12),
    IMPORTE VARCHAR2(12)NOT NULL,
    BANNER VARCHAR2(12),
    ESCUDID VARCHAR2(12) NOT NULL,
    DNI VARCHAR2(2) NOT NULL,
    FOREIGN KEY(DNI) REFERENCES EMPLEADOS,
    FOREIGN KEY(DNI) REFERENCES ORG_MARKETING,
    FOREIGN KEY(ESCUDID) REFERENCES ESCUD,
    PRIMARY KEY(NSS)
);

CREATE TABLE PERSONA(
    DNI VARCHAR2(9)NOT NULL,
    NOMBRE VARCHAR2(12),
    NSS VARCHAR2(12) NOT NULL,
    FOREIGN KEY(NSS) REFERENCES PATROCINADORES,
    PRIMARY KEY(DNI)
);

CREATE TABLE EMPRESA(
    ID_EMPRESA VARCHAR2(12)NOT NULL,
    NOMBRE VARCHAR2(12),
    NSS VARCHAR2(12) NOT NULL,
    FOREIGN KEY(NSS) REFERENCES PATROCINADORES,
    PRIMARY KEY(ID_EMPRESA)
);

CREATE TABLE ENTREN
(
    IDENTREN    VARCHAR (15),
    ENTRENCOND  VARCHAR (30),
    ENTRENREND  VARCHAR (10),
    IDGP        VARCHAR2(12),
    PRIMARY KEY(IDENTREN),
    FOREIGN KEY (IDGP) REFERENCES GP
);

CREATE TABLE CARRERA
(
    IDCARRERA VARCHAR2(12),
    POSCARRERA  VARCHAR2(12),
    IDGP        VARCHAR2(12),
    PRIMARY KEY(IDCARRERA),
    FOREIGN KEY (IDGP) REFERENCES GP
);


CREATE TABLE COMPONENTES(
    ID_COMPONENTE NUMBER(6) NOT NULL,
    NUM_PIEZA NUMBER(6) NOT NULL,
    NUM_VERSION NUMBER(6) NOT NULL,
    FECHA_FABRICACION DATE NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL,
    PRIMARY KEY(ID_COMPONENTE),
    FOREIGN KEY(NUM_PIEZA,NUM_VERSION) REFERENCES VERSION
    
);
CREATE TABLE MOTOR(
    ID_MOTOR NUMBER(6) NOT NULL,
    ID_COMPONENTE NUMBER(6),
    MODELO VARCHAR2(10) NOT NULL,
    PRECIO NUMBER(9) NOT NULL,
    FABRICANTE VARCHAR2(10) NOT NULL,
    CONFIGURACION VARCHAR2(10) NOT NULL,
    CONSUMO NUMBER(6) NOT NULL,
    PRIMARY KEY(ID_MOTOR),
    FOREIGN KEY(ID_COMPONENTE) REFERENCES COMPONENTES
    
);

CREATE TABLE CAJA_DE_CAMBIOS(
    ID_CAJADECAMBIOS NUMBER(6) NOT NULL,
    ID_COMPONENTE NUMBER(6),
    CONFIGURACION VARCHAR2(10) NOT NULL,
    MODELO VARCHAR2(10) NOT NULL,
    RELACION NUMBER(6) NOT NULL,
    PRIMARY KEY(ID_CAJADECAMBIOS),
    FOREIGN KEY(ID_COMPONENTE) REFERENCES COMPONENTES
    
);

CREATE TABLE SUSPENSION(
    ID_SUSPENSION NUMBER(6) NOT NULL,
    ID_COMPONENTE NUMBER(6),
    CONFIGURACION VARCHAR2(10) NOT NULL,
    PRIMARY KEY(ID_SUSPENSION),
    FOREIGN KEY(ID_COMPONENTE) REFERENCES COMPONENTES
    
    
);

CREATE TABLE FRENOS(
    ID_FRENOS NUMBER(6) NOT NULL,
    ID_COMPONENTE NUMBER(6),
    CONFIGURACION VARCHAR2(10) NOT NULL,
    MATERIAL VARCHAR2(10) NOT NULL,
    PRIMARY KEY(ID_FRENOS),
    FOREIGN KEY(ID_COMPONENTE) REFERENCES COMPONENTES

);

CREATE TABLE KIT_AERO(
    ID_KITAERO NUMBER(6) NOT NULL,
    ID_COMPONENTE NUMBER(6),
    CONFIGURACION VARCHAR2(10) NOT NULL,
    PRIMARY KEY(ID_KITAERO),
    FOREIGN KEY(ID_COMPONENTE) REFERENCES COMPONENTES
);

CREATE TABLE COBERTURA_MOTOR(
    ID_COBERTURAMOTOR NUMBER(6) NOT NULL,
    ID_COMPONENTE NUMBER(6),
    ID_COBERTURA_MOTOR NUMBER(6) NOT NULL,
    PRIMARY KEY(ID_COBERTURAMOTOR),
    FOREIGN KEY(ID_COMPONENTE) REFERENCES COMPONENTES
);

CREATE TABLE PONTON(
    ID_PONTON NUMBER(6) NOT NULL,
    ID_COMPONENTE NUMBER(6),
    PRIMARY KEY(ID_PONTON),
    FOREIGN KEY(ID_COMPONENTE) REFERENCES COMPONENTES

);

CREATE TABLE ALERON_DEL(
    ID_ALERONDEL NUMBER(6) NOT NULL,
    ID_COMPONENTE NUMBER(6),
    PRIMARY KEY(ID_ALERONDEL),
    FOREIGN KEY(ID_COMPONENTE) REFERENCES COMPONENTES

);

CREATE TABLE ALERON_TRAS(
    ID_ALERONTRAS NUMBER(6) NOT NULL,
    ID_COMPONENTE NUMBER(6),
    PRIMARY KEY(ID_ALERONTRAS),
    FOREIGN KEY(ID_COMPONENTE) REFERENCES COMPONENTES

);

CREATE TABLE MGU_K(
    ID_MGUK NUMBER(6) NOT NULL,
    ID_COMPONENTE NUMBER(6),
    CAPACIDAD NUMBER(6) NOT NULL,
    CONFIGURACION VARCHAR2(10) NOT NULL,
    PRIMARY KEY(ID_MGUK),
    FOREIGN KEY(ID_COMPONENTE) REFERENCES COMPONENTES
);

CREATE TABLE MGU_H(
    ID_MGUH NUMBER(6) NOT NULL,
    ID_COMPONENTE NUMBER(6),
    DIAMETRO_TURBINA NUMBER(6) NOT NULL,
    CONFIGURACION VARCHAR2(10) NOT NULL,
    PRIMARY KEY(ID_MGUH),
    FOREIGN KEY(ID_COMPONENTE) REFERENCES COMPONENTES
);

CREATE TABLE BATERIA(
    ID_BATERIA NUMBER(6) NOT NULL,
    ID_COMPONENTE NUMBER(6),
    CAPACIDAD NUMBER(6) NOT NULL,
    MODELO VARCHAR2(10) NOT NULL,
    PRIMARY KEY(ID_BATERIA),
    FOREIGN KEY(ID_COMPONENTE) REFERENCES COMPONENTES
);

CREATE TABLE NEUMATICOS(
    ID_NEUMATICOS NUMBER(6) NOT NULL,
    ID_COMPONENTE NUMBER(6),
    ESTADO VARCHAR2(10)NOT NULL,
    MODELO VARCHAR2(10) NOT NULL,
    COMPUESTO VARCHAR2(10) NOT NULL,
    FECHA_FABRICACION DATE NOT NULL,
    PRIMARY KEY(ID_NEUMATICOS),
    FOREIGN KEY(ID_COMPONENTE) REFERENCES COMPONENTES
);

CREATE TABLE SLICS(
    ID_NEUMATICOS NUMBER(6) NOT NULL,
    TIPO VARCHAR2(10) NOT NULL,
    PRIMARY KEY(ID_NEUMATICOS),
    FOREIGN KEY(ID_NEUMATICOS) REFERENCES NEUMATICOS
);

CREATE TABLE WET(
    ID_NEUMATICOS NUMBER(6) NOT NULL,
    ESTRIADO VARCHAR2(10) NOT NULL,
    ESTADO_PISTA VARCHAR2(10) NOT NULL,
    PRIMARY KEY(ID_NEUMATICOS),
    FOREIGN KEY(ID_NEUMATICOS) REFERENCES NEUMATICOS
);

/*******************************************************/
/* 3.- Creamos los índices necesarios sobre las tablas */
/*******************************************************/

CREATE INDEX Estado_Neumaticos 
ON NEUMATICOS (ESTADO,MODELO,FECHA_FABRICACION);

/************************************************/
/* 4.- Creamos las vistas para nuestra temática */
/************************************************/

CREATE OR REPLACE VIEW V_PIEZAS (NUMERO_PIEZA, NUMERO_VERSION,ID_COMPONENTE,FECHA_FABRICACION,ESTADO)
    AS SELECT NUM_PIEZA, NUM_VERSION, ID_COMPONENTE, FECHA_FABRICACION, ESTADO
    FROM COMPONENTES;

CREATE OR REPLACE VIEW V_EMPLEADOS (DNI, NOMBRE, APELLIDOS, NUM_SS, DIRECCION, INICIO_CONTRATO, SUELDO)
    AS SELECT DNI, NOMBRE, APELLIDOS, NSS, DIRECCION, F_INICIOCONTRATO, SUELDO
    FROM EMPLEADOS;

CREATE OR REPLACE VIEW V_COCHES (IDCOCHE, ESTADO_COCHE, FECHA_MONTAJE, PESO_COCHE)
    AS SELECT IDCOCHE, ESTADOCOCHE, FECHAMONTAJE, PESOCOCHE
    FROM COCHE;

/*********************************************************/
/* 5.- Insertamos datos de ejemplo para todas las tablas */
/*********************************************************/

INSERT INTO ESCUD (ESCUDID, ESCUDNAME, ESCUDPUNT, ESCUDPRESU) VALUES ('1234G','ESCUDERIA', '1302', '15000');

INSERT INTO COCHE (IDCOCHE, FECHAMONTAJE, PESOCOCHE, PRECIOCOCHE, ESTADOCOCHE, ESCUDID) VALUES('COCHE1', '11-05-2019', 356, 50000, 'NUEVO', '1234G' );
INSERT INTO COCHE (IDCOCHE, FECHAMONTAJE, PESOCOCHE, PRECIOCOCHE, ESTADOCOCHE, ESCUDID) VALUES('COCHE2', '11-08-2017', 356, 30000, 'USADO', '1234G' );

INSERT INTO GP (IDGP,FECHAGP, LOCGP) VALUES('12345', '15-02-2023', 'OURENSE');

INSERT INTO ENTREN (IDENTREN,ENTRENCOND, ENTRENREND, IDGP) VALUES ('ENTREN1', 'CON LLUVIA', '78', '12345');
INSERT INTO ENTREN (IDENTREN,ENTRENCOND, ENTRENREND, IDGP) VALUES ('ENTREN2', 'VIENTO', '93', '12345');
INSERT INTO ENTREN (IDENTREN,ENTRENCOND, ENTRENREND, IDGP) VALUES ('ENTREN3', 'CON LLUVIA', '82', '12345');
INSERT INTO ENTREN (IDENTREN,ENTRENCOND, ENTRENREND, IDGP) VALUES ('ENTREN4', 'SOL', '97', '12345');

INSERT INTO CARRERA (IDCARRERA,POSCARRERA,IDGP) VALUES ('135G', 'JUAN 1', '12345'); 
INSERT INTO CARRERA (IDCARRERA,POSCARRERA,IDGP) VALUES ('134G', 'PEDRO 1', '12345'); 
INSERT INTO CARRERA (IDCARRERA,POSCARRERA,IDGP) VALUES ('136G', 'LAURA 1', '12345');

INSERT INTO PIEZA (NUM_PIEZA) VALUES ('1001');
INSERT INTO PIEZA (NUM_PIEZA) VALUES ('1002');
INSERT INTO PIEZA (NUM_PIEZA) VALUES ('1003');


INSERT INTO VERSION (NUM_PIEZA,NUM_VERSION) VALUES ('1001','0001');
INSERT INTO VERSION (NUM_PIEZA,NUM_VERSION) VALUES ('1001','0002');
INSERT INTO VERSION (NUM_PIEZA,NUM_VERSION) VALUES ('1002','0001');
INSERT INTO VERSION (NUM_PIEZA,NUM_VERSION) VALUES ('1002','0002');
INSERT INTO VERSION (NUM_PIEZA,NUM_VERSION) VALUES ('1003','0001');
INSERT INTO VERSION (NUM_PIEZA,NUM_VERSION) VALUES ('1003','0002');


/********************************************/
/* 6.- Incluímos sentencias de comprobación */
/********************************************/

Select * from escud;

Select * from gp;

Select * from coche;

Select * from carrera;

Select * from entren;

Select * from pilotos;

Select * from setup;

Select * from pieza;

Select * from componentes;

Select * from empleados;

Select * from version;

Select * from patrocinadores;

Select * from org_marketing;

Select * from analistas;

Select * from tecnicos;

Select * from persona;

Select * from empresa;
